version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - mongo
    environment:
      FLASK_ENV: development
      FLASK_APP: app.py

  mongo:
    image: mongo
    ports:
      - "27017:27017"
